[package]
name = "test_util"
version = "0.0.1"
publish = false

[dependencies]
tikv = { path = "../../" }
tikv_log = { path = "../tikv_log" }
tikv_logger = { path = "../tikv_logger" }
time = "0.1"
rand = "0.5"
slog = "2.4"
