[package]
name = "tikv_log"
version = "0.0.1"
publish = false

[dependencies]
lazy_static = { version = "1.2", features = ["nightly"] }
slog = "2.4"
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0692aee" }

